apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-route
spec:
  to:
    kind: Service
    name: product-srv
  port:
    targetPort: 8050
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
    destinationCACertificate: {{ (lookup "v1" "ConfigMap" "test-project" "my-config").data }}
