apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-route
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: tls-secret
spec:
  to:
    kind: Service
    name: product-srv
  port:
    targetPort: 8050
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
