apiVersion: v1
kind: Service
metadata:
  name: "product-srv"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
